version: '3.9'

services:
  db:
    image: postgres:15
    container_name: bookorder_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bookorder_app
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  db_data:
